const product_card = [
  {
    id: 1,
    name: "Rayes Alpha",
    description: "Hands-free, Hads-on Mushc Experience",
    buyNowPrice: 350,
    currency: "$",
    imageURL: "./images/1.png",
  },
  {
    id: 2,
    name: "Rayes Z30",
    description: "Hands-free, Hads-on Mushc Experience",
    buyNowPrice: 250,
    currency: "$",
    imageURL: "./images/2.png",
  },
  {
    id: 3,
    name: "Rayes X30",
    description: "Hands-free, Hads-on Mushc Experience",
    buyNowPrice: 350,
    currency: "$",
    imageURL: "./images/3.png",
  },
  {
    id: 4,
    name: "Rayes Alpha",
    description: "Hands-free, Hads-on Mushc Experience",
    buyNowPrice: 350,
    currency: "$",
    imageURL: "./images/1.png",
  },
  {
    id: 5,
    name: "Rayes Z30",
    description: "Hands-free, Hads-on Mushc Experience",
    buyNowPrice: 250,
    currency: "$",
    imageURL: "./images/2.png",
  },
  {
    id: 6,
    name: "Rayes X30",
    description: "Hands-free, Hads-on Mushc Experience",
    buyNowPrice: 350,
    currency: "$",
    imageURL: "./images/3.png",
  },
  {
    id: 7,
    name: "Rayes Alpha",
    description: "Hands-free, Hads-on Mushc Experience",
    buyNowPrice: 350,
    currency: "$",
    imageURL: "./images/1.png",
  },
  {
    id: 8,
    name: "Rayes Z30",
    description: "Hands-free, Hads-on Mushc Experience",
    buyNowPrice: 250,
    currency: "$",
    imageURL: "./images/2.png",
  },
  {
    id: 9,
    name: "Rayes X30",
    description: "Hands-free, Hads-on Mushc Experience",
    buyNowPrice: 350,
    currency: "$",
    imageURL: "./images/3.png",
  },
];
export default product_card;
